name: BlepFishing
main: com.kunfury.blepFishing.Setup
version: 1.10.3
api-version: 1.13
author: Kunfury
softdepend: [Vault, mcMMO, PlaceholderAPI, WorldGuard]
commands:
   bf:
      description: The base command for the plugin
      usage: /bf
      aliases: [BlepFish]
permissions:
   bf.*:
      description: Gives access to all Blep commands
      children:
         bf.reload: true
         bf.admin: true
         bf.listFish: true
   bf.reload:
      description: Allows you to reload blep fishing
   bf.admin:
      description: Gives access to the admin panel
   bf.listFish:
      description: Gives the player access to the fish command
   bf.sell:
      description: Gives access to the sell command
   bf.sellall:
      description: Gives access to the sellall command
   bf.sellfor:
      description: Gives access to the sellfor command