name: BlepFishing
main: com.kunfury.blepFishing.Setup
version: 1.6.5
api-version: 1.13
softdepend: [Vault]
commands:
   BlepFish:
      description: The base command for the plugin
      usage: /BlepFish
   bf:
      description: The base command for the plugin
      usage: /bf
   bf reload:
      description: Reloads the blep fishing plugin
      usage: /bf reload
permissions:
   bf.*:
      description: Gives access to all Blep commands
      children:
         bf.reload: true
         bf.admin: true
         bf.listFish: true
   bf.reload:
      description: Allows you to reload blep fishing
   bf.admin:
      description: Gives access to the admin panel
   bf.listFish:
      description: Gives the player access to the fish command
   bf.sell:
      description: Gives access to the sell command
   bf.sellall:
      description: Gives access to the sellall command
   bf.sellfor:
      description: Gives access to the sellfor command